// File: cacheFSM.v
// Generated by MyHDL 0.9.0
// Date: Sun Nov  8 14:55:23 2015


`timescale 1ns/10ps

module cacheFSM (
    r,
    w,
    clk,
    state
);
// Function contains finite state machine definition
// 
// :param r:     input read
// :param w:     input write
// :param clk:   clock
// :param state: current state

input r;
input w;
input clk;
output [1:0] state;
reg [1:0] state;






always @(posedge clk) begin: CACHEFSM_LOGIC
    if (((r == 1) && (w == 0))) begin
        state <= 2'b01;
    end
    else if (((w == 1) && (r == 0))) begin
        state <= 2'b10;
    end
    else begin
        state <= 2'b00;
    end
end

endmodule
